### ISSUE TITLE
xsd:time not supported

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/salesforce-component#13]
https://github.com/elasticio/salesforce-component/blob/587b45de9f68b050c5d500f4f6826c97cba3ebea/lib/helpers/metadata.js#L6

We need to add additional type as `xsd:time = string`

https://github.com/elasticio/salesforce-component/blob/587b45de9f68b050c5d500f4f6826c97cba3ebea/lib/helpers/metadata.js#L28

This gives an error like:

```
Starting your Docker container ...
Starting application in apprunner
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Detected 256 MB available memory
Detected 0.1 CPU available
Starting the application with node ./node_modules/elasticio-sailor-nodejs/runService.js getMetaModel
Sending post request to https://login.salesforce.com/services/oauth2/token
Have got 200 response from post to https://login.salesforce.com/services/oauth2/token
Refreshed token from https://{{prodEnv}}.salesforce.com/services/oauth2/token
Sending get request to https://eu9.salesforce.com/services/data/v25.0/sobjects/Port_of_Call__c/describe
Have got 200 response from get to https://eu9.salesforce.com/services/data/v25.0/sobjects/Port_of_Call__c/describe
at _fieldToProperty (/app/lib/helpers/metadata.js:28:15)
Exception happened when passing data down the chain Error: Can't conver salesforce soapType xsd:time to JSON schema type
at addProperty (/app/lib/helpers/metadata.js:81:35)
at arrayEach (/app/node_modules/lodash/lodash.js:537:11)
at Object.buildSchemaFromDescription (/app/lib/helpers/metadata.js:79:7)
at buildMetadata (/app/lib/entry.js:57:53)
at Function.forEach (/app/node_modules/lodash/lodash.js:9359:14)
at Request.self.callback (/app/node_modules/request/request.js:188:22)
at Request.checkResponse [as _callback] (/app/lib/helpers/http-utils.js:76:21)
at Request.emit (events.js:191:7)
at emitTwo (events.js:106:13)
Starting application in apprunner
Starting slug download ...
Successfully downloaded and extracted slug file
Writing config vars to .profile.d/config_vars
Detected 0.1 CPU available
Detected 256 MB available memory
Starting the application with node ./node_modules/elasticio-sailor-nodejs/runService.js getMetaModel
Sending post request to https://login.salesforce.com/services/oauth2/token
Have got 200 response from post to https://login.salesforce.com/services/oauth2/token
Refreshed token from https://{{prodEnv}}.salesforce.com/services/oauth2/token
Sending get request to https://eu9.salesforce.com/services/data/v25.0/sobjects/Port_of_Call__c/describe
Have got 200 response from get to https://eu9.salesforce.com/services/data/v25.0/sobjects/Port_of_Call__c/describe
at _fieldToProperty (/app/lib/helpers/metadata.js:28:15)
Exception happened when passing data down the chain Error: Can't conver salesforce soapType xsd:time to JSON schema type
at addProperty (/app/lib/helpers/metadata.js:81:35)
at arrayEach (/app/node_modules/lodash/lodash.js:537:11)
at Function.forEach (/app/node_modules/lodash/lodash.js:9359:14)
at Object.buildSchemaFromDescription (/app/lib/helpers/metadata.js:79:7)
at buildMetadata (/app/lib/entry.js:57:53)
at Request.checkResponse [as _callback] (/app/lib/helpers/http-utils.js:76:21)
at Request.self.callback (/app/node_modules/request/request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
```

**Comment by khanzadyan** [comment]
And maybe you could correct the spelling of the message as well :)
