### ISSUE TITLE
Errors when tries to fetch the dynamic metadata

### ISSUE THREAD

**Issue by khanzadyan** [elasticio/salesforce-component#51]
This error is not particularly a blocking issue but, nevertheless is visible.

When you have already configured and published flow and you are opening the flow page the logs windows appears probably to fetch the dynamic metadata and or connect to Salesforce. The logs window contains the following:
```
Starting your Docker container ...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Starting application in apprunner...
Starting slug download ...
Successfully downloaded and extracted slug file
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
Sending post request to https://login.salesforce.com/services/oauth2/token
Have got 200 response from post to https://login.salesforce.com/services/oauth2/token
Refreshed token from https://{{prodEnv}}.salesforce.com/services/oauth2/token
Sending get request to https://na38.salesforce.com/services/data/v25.0/sobjects/Lead/describe
Have got 200 response from get to https://na38.salesforce.com/services/data/v25.0/sobjects/Lead/describe
at provideOptions (/home/apprunner/node_modules/elasticio-rest-node/lib/resource.js:79:20)
at self.promiseDispatch.done (/home/apprunner/node_modules/q/q.js:883:30)
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickCallback (internal/process/next_tick.js:181:9) ]
Error: Missing value for parameter '{id}'. Please provide argument: 0
at interpolatePath (/home/apprunner/node_modules/elasticio-rest-node/lib/resource.js:129:23)
at _fulfilled (/home/apprunner/node_modules/q/q.js:854:54)
at process._tickCallback (internal/process/next_tick.js:181:9) 0 [ Error: Missing value for parameter '{id}'. Please provide argument: 0
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at _fulfilled (/home/apprunner/node_modules/q/q.js:854:54)
at Promise.promise.promiseDispatch (/home/apprunner/node_modules/q/q.js:816:13)
at runSingle (/home/apprunner/node_modules/q/q.js:137:13)
at flush (/home/apprunner/node_modules/q/q.js:125:13)
at provideOptions (/home/apprunner/node_modules/elasticio-rest-node/lib/resource.js:79:20)
at /home/apprunner/node_modules/q/q.js:877:14
at runSingle (/home/apprunner/node_modules/q/q.js:137:13)
at /home/apprunner/node_modules/q/q.js:877:14
at self.promiseDispatch.done (/home/apprunner/node_modules/q/q.js:883:30)
at Promise.promise.promiseDispatch (/home/apprunner/node_modules/q/q.js:816:13)
at flush (/home/apprunner/node_modules/q/q.js:125:13)
at interpolatePath (/home/apprunner/node_modules/elasticio-rest-node/lib/resource.js:129:23)
[INFO  tini (1)] Main child exited normally (with status '0')
```

**Comment by shulkaolka** [comment]
After investigation, it turned out that the problem is on the platform side [issue 714](https://github.com/elasticio/platform/issues/714)
