### ISSUE TITLE
Objects types: Document and Attachment can not be created with the component

### ISSUE THREAD

**Issue by stas-fomenko** [elasticio/salesforce-component#66]
**Description:** Error is shown after object types  `Document` and Attachment were selected

**STR:**
1. Create flow: simple trigger -> Salesforce
2. Select action `Create Object` and choose `Document` in dropdown list
3. See Error message.
4. Repeat steps 2 and 3 for object type: `Attachment`
5. Pay attention to error message in logs: `Exception happened when passing data down the chain Error: Can't convert salesforce soapType xsd:base64Binary to JSON schema type
`

**AR:**

Error message for `Document`: ` Error: Execution timeout Please see logs for more details.`
Logs:
```
Starting your Docker container ...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Starting application in apprunner...
Starting slug download ...
Successfully downloaded and extracted slug file
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
Sending post request to https://login.salesforce.com/services/oauth2/token
Have got 200 response from post to https://login.salesforce.com/services/oauth2/token
Refreshed token from https://{{prodEnv}}.salesforce.com/services/oauth2/token
Sending get request to https://na98.salesforce.com/services/data/v25.0/sobjects/Document/describe
Have got 200 response from get to https://na98.salesforce.com/services/data/v25.0/sobjects/Document/describe
at Function.forEach (/home/apprunner/node_modules/lodash/lodash.js:9344:14)
at emitTwo (events.js:126:13)
Exception happened when passing data down the chain Error: Can't convert salesforce soapType xsd:base64Binary to JSON schema type
at arrayEach (/home/apprunner/node_modules/lodash/lodash.js:516:11)
at buildMetadata (/home/apprunner/lib/entry.js:60:47)
at _fieldToProperty (/home/apprunner/lib/helpers/metadata.js:29:11)
at addProperty (/home/apprunner/lib/helpers/metadata.js:85:31)
at Object.buildSchemaFromDescription (/home/apprunner/lib/helpers/metadata.js:83:5)
at Request.checkResponse [as _callback] (/home/apprunner/lib/helpers/http-utils.js:76:21)
at Request.self.callback (/home/apprunner/node_modules/request/request.js:185:22)
at Request.emit (events.js:214:7)
[INFO  tini (1)] Main child exited normally (with status '0')
```

Error message for `Attachment`: ` Error: Execution timeout Please see logs for more details.`

Logs:
```
Starting your Docker container ...
[INFO  tini (1)] Spawned child process '/run.sh' with pid '7'
Starting application in apprunner...
Starting slug download ...
Successfully downloaded and extracted slug file
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
node: /usr/lib/libstdc++.so.6: no version information available (required by node)
Sending post request to https://login.salesforce.com/services/oauth2/token
Have got 200 response from post to https://login.salesforce.com/services/oauth2/token
Refreshed token from https://{{prodEnv}}.salesforce.com/services/oauth2/token
Sending get request to https://na98.salesforce.com/services/data/v25.0/sobjects/Attachment/describe
Have got 200 response from get to https://na98.salesforce.com/services/data/v25.0/sobjects/Attachment/describe
at addProperty (/home/apprunner/lib/helpers/metadata.js:85:31)
at arrayEach (/home/apprunner/node_modules/lodash/lodash.js:516:11)
at buildMetadata (/home/apprunner/lib/entry.js:60:47)
at Function.forEach (/home/apprunner/node_modules/lodash/lodash.js:9344:14)
at Object.buildSchemaFromDescription (/home/apprunner/lib/helpers/metadata.js:83:5)
at Request.checkResponse [as _callback] (/home/apprunner/lib/helpers/http-utils.js:76:21)
at Request.self.callback (/home/apprunner/node_modules/request/request.js:185:22)
Exception happened when passing data down the chain Error: Can't convert salesforce soapType xsd:base64Binary to JSON schema type
at _fieldToProperty (/home/apprunner/lib/helpers/metadata.js:29:11)
at emitTwo (events.js:126:13)
at Request.emit (events.js:214:7)
[INFO  tini (1)] Main child exited normally (with status '0')
```

**ER:**
Object with chosen object type is created accordingly to input data

**Comment by FlorianJansen1337** [comment]
Only happens on Flowground for me. But also happens with:

> Content Version
> Feed Item
> Mail Merge Template
> Custom S-Control
> Static Resource

**Comment by A3a3e1** [comment]
Looks like a duplicate for another task which was already done. But should check ai along with Florian's comment above

**Comment by dvd-z** [comment]
Works for me, not seeing any errors after selecting object types `Document` or `Attachment`

**Comment by stas-fomenko** [comment]
@A3a3e1 

>Looks like a duplicate for another task which was already done. But should check ai along with Florian's comment above

Valid requests are needed for this, as Florian didn't paste them here.
I tried to found a couple, but with no success, however, for `Content Version` following request causes an error:

**Request:**
```
{
  "ContentDocumentId": "0692R000005digDQAQ",
  "Title":"test1",
  "ContentUrl": "https://na98.lightning.force.com/lightning/r/ContentDocument/0692R000005digDQAQ",
  "Origin": "C"
}
```
**Error in logs:** 
`statusCode: 400 } Error: Unexpected return code 400, expected 201, body [{"message":"You can't create a new Content Version of the Content Document because the new Content Version is incompatible with the Content Document's Content Versioning Policy. Try uploading a new Content Document instead of versioning an existing Content Document.","errorCode":"INVALID_STATUS","fields":[]}]`

and it does not look like the component bug, but Salesforce instance behavior

**Comment by stas-fomenko** [comment]
![image](https://user-images.githubusercontent.com/36419533/65436992-4e46df80-de23-11e9-9c11-f3437997d6bb.png)
https://elasticio.slack.com/archives/CNGHLMAET/p1568973796015300
